/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: (typeof import('./../views/AboutView.vue'))['default'];
    ElButton: (typeof import('element-plus/es'))['ElButton'];
    ElButtonGroup: (typeof import('element-plus/es'))['ElButtonGroup'];
    ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox'];
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider'];
    ElForm: (typeof import('element-plus/es'))['ElForm'];
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem'];
    ElInput: (typeof import('element-plus/es'))['ElInput'];
    ElLink: (typeof import('element-plus/es'))['ElLink'];
    ElSpace: (typeof import('element-plus/es'))['ElSpace'];
    ElText: (typeof import('element-plus/es'))['ElText'];
    HeaderLayout: (typeof import('./../components/layouts/HeaderLayout.vue'))['default'];
    HomeView: (typeof import('./../views/HomeView.vue'))['default'];
    IconCommunity: (typeof import('./../components/icons/IconCommunity.vue'))['default'];
    IconDocumentation: (typeof import('./../components/icons/IconDocumentation.vue'))['default'];
    IconEcosystem: (typeof import('./../components/icons/IconEcosystem.vue'))['default'];
    IconSupport: (typeof import('./../components/icons/IconSupport.vue'))['default'];
    IconText: (typeof import('./../components/IconText/IconText.vue'))['default'];
    IconTooling: (typeof import('./../components/icons/IconTooling.vue'))['default'];
    IEpLock: (typeof import('~icons/ep/lock'))['default'];
    IEpUser: (typeof import('~icons/ep/user'))['default'];
    IUiwAlipay: (typeof import('~icons/uiw/alipay'))['default'];
    IUiwQq: (typeof import('~icons/uiw/qq'))['default'];
    IUiwWeibo: (typeof import('~icons/uiw/weibo'))['default'];
    IUiwWeixin: (typeof import('~icons/uiw/weixin'))['default'];
    LoginForm: (typeof import('./../views/login/LoginForm.vue'))['default'];
    LoginView: (typeof import('./../views/login/LoginView.vue'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    TheFooter: (typeof import('./../components/layouts/TheFooter.vue'))['default'];
  }
}
